#端口号配置
server:
  port: ${PORT:8089}

#数据库连接配置（云端自动适配，不用改密码）
spring:
  main:
    allow-circular-references: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}

# 图片上传配置（云端自动路径，不用你本地D盘）
web:
  uploadpath: /app/images/queue-system/
  load-path: file:/app/images/queue-system/

#mybatis plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      update-strategy: not_empty

#日志
logging:
  pattern:
    console: '%d{yyyy-MM-dd} [%thread] %-5level %logger- %msg%n'